server:
  port: 8003
spring:
  application:
    name: cloud-provider-hystrix-payment #相当于第三方支付功能的提供者CLOUD-PROVIDER-HYSTRIX-PAYMENT
eureka:
  client:
    #false表示不向注册中心注册自己
    register-with-eureka: true
    #表示是否从Eureka Server获取注册信息，默认为true(集群的时候，有了服务列表，这样配合ribbon使用负载均衡，调用提供服务的多个机器）; 注册中心，不要ribbon的，要负载均衡的是其它注册到中心的)。
    #如果这是一个单点的 Eureka Server，不需要同步其他节点的数据，可以设为false
    fetch-registry: true
    # 设置与注册中心的交互地址
    service-url:
      defaultZone: http://127.0.0.1:7003/eureka/