server:
  port: 80

#这里只把feign做客户端用，不注册进eureka
eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: false
    # 服务注册中心的地址，虽然没有注册进去，还是使用到了，源码...,不然负载均衡，怎么去找名称下面的实例的url
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/

#设置feign客户端超时时间（OpenFeign默认支持ribbon，看来是通过ribbon控制的时间）
#默认等待时间是1秒，超过一秒会报错，通过ribbon控制时间
ribbon:
  #指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的实际
  ReadTimeout: 5000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000

logging:
  level:
    #feign日志以什么级别监控那个接口（自己写的接口，调用远程的方法）
    com.songbl.springcloud.service.PaymentFeignService: debug